package fi.hut.soberit.agilefant.transfer;

import fi.hut.soberit.agilefant.model.ExactEstimate;

public class IterationMetrics {
//    private AFTime dailyVelocity = new AFTime(0);
//    private AFTime scopingNeeded = new AFTime(0);
//  private Integer scheduleVariance = new Integer(0);
    private ExactEstimate effortLeft = new ExactEstimate(0);
    private ExactEstimate originalEstimate = new ExactEstimate(0);
    private ExactEstimate spentEffort = new ExactEstimate(0);
    private Integer storyPoints = new Integer(0);

    private Integer completedTasks = new Integer(0);
    private Integer totalTasks = new Integer(0);
    private Integer percentDone = new Integer(0);
    private boolean backlogOngoing = true;
    private ExactEstimate dailyVelocity = new ExactEstimate(0);
    
    
    /*
     * Autogenerated list of getters and setters
     */
    
    public Integer getPercentDone() {
        return percentDone;
    }
    public void setPercentDone(Integer percentDone) {
        this.percentDone = percentDone;
    }
    public boolean isBacklogOngoing() {
        return backlogOngoing;
    }
    public void setBacklogOngoing(boolean backlogOngoing) {
        this.backlogOngoing = backlogOngoing;
    }
    public void setEffortLeft(ExactEstimate effortLeft) {
        this.effortLeft = effortLeft;
    }
    public ExactEstimate getEffortLeft() {
        return effortLeft;
    }
    public void setOriginalEstimate(ExactEstimate originalEstimate) {
        this.originalEstimate = originalEstimate;
    }
    public ExactEstimate getOriginalEstimate() {
        return originalEstimate;
    }
    public void setSpentEffort(ExactEstimate spentEffort) {
        this.spentEffort = spentEffort;
    }
    public ExactEstimate getSpentEffort() {
        return spentEffort;
    }
    public void setStoryPoints(Integer storyPoints) {
        this.storyPoints = storyPoints;
    }
    public Integer getStoryPoints() {
        return storyPoints;
    }
    public void setCompletedTasks(Integer completedTasks) {
        this.completedTasks = completedTasks;
    }
    public Integer getCompletedTasks() {
        return completedTasks;
    }
    public void setTotalTasks(Integer totalTasks) {
        this.totalTasks = totalTasks;
    }
    public Integer getTotalTasks() {
        return totalTasks;
    }
    public ExactEstimate getDailyVelocity() {
        return dailyVelocity;
    }
    public void setDailyVelocity(ExactEstimate dailyVelocity) {
        this.dailyVelocity = dailyVelocity;
    }

}
