package fi.hut.soberit.agilefant.util;

import fi.hut.soberit.agilefant.model.AFTime;

public class BacklogMetrics {
    private AFTime dailyVelocity = new AFTime(0);
    private AFTime scopingNeeded = new AFTime(0);
    private Integer scheduleVariance = new Integer(0);
    
    /*
     * Autogenerated list of getters and setters
     */
    
    public AFTime getDailyVelocity() {
        return dailyVelocity;
    }
    public void setDailyVelocity(AFTime dailyVelocity) {
        this.dailyVelocity = dailyVelocity;
    }
    public AFTime getScopingNeeded() {
        return scopingNeeded;
    }
    public void setScopingNeeded(AFTime scopingNeeded) {
        this.scopingNeeded = scopingNeeded;
    }
    public Integer getScheduleVariance() {
        return scheduleVariance;
    }
    public void setScheduleVariance(Integer scheduleVariance) {
        this.scheduleVariance = scheduleVariance;
    }
}
