package fi.hut.soberit.agilefant.util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import fi.hut.soberit.agilefant.model.Backlog;

/**
 * Carrier class to bring lefthand menu data to action. 
 * @author rjokelai
 *
 */
public class MenuData {
    
    private List<Backlog> menuItems = new ArrayList<Backlog>();
    private Map<Backlog, Boolean> hasChildren = new HashMap<Backlog, Boolean>();
    private Map<Backlog, String> objectTypes = new HashMap<Backlog, String>();
    
    /*
     * Autogenerated list of setters and getters.
     */
    public List<Backlog> getMenuItems() {
        return menuItems;
    }

    public void setMenuItems(List<Backlog> menuItems) {
        this.menuItems = menuItems;
    }

    public Map<Backlog, Boolean> getHasChildren() {
        return hasChildren;
    }

    public void setHasChildren(Map<Backlog, Boolean> hasChildren) {
        this.hasChildren = hasChildren;
    }

    public Map<Backlog, String> getObjectTypes() {
        return objectTypes;
    }

    public void setObjectTypes(Map<Backlog, String> objectTypes) {
        this.objectTypes = objectTypes;
    }
}
