package fi.hut.soberit.agilefant.util;

public enum StoryHierarchyIntegrityViolationType {
    CHILD_IN_WRONG_BRANCH, MOVE_TO_ITERATION_HAS_CHILDREN, PARENT_DEEPER_IN_HIERARCHY, 
    PARENT_IN_WRONG_BRANCH, TARGET_PARENT_IN_WRONG_BRANCH, PARENT_IN_WRONG_PRODUCT,
    TARGET_PARENT_DEEPER_IN_HIERARCHY, 
    TARGET_PARENT_IN_ITERATION
}
