package fi.hut.soberit.agilefant.business.impl;

import java.util.List;

import fi.hut.soberit.agilefant.business.IterationBusiness;
import fi.hut.soberit.agilefant.db.BacklogItemDAO;
import fi.hut.soberit.agilefant.db.BusinessThemeDAO;
import fi.hut.soberit.agilefant.db.IterationDAO;
import fi.hut.soberit.agilefant.db.IterationGoalDAO;
import fi.hut.soberit.agilefant.model.Iteration;
import fi.hut.soberit.agilefant.model.IterationGoal;
import fi.hut.soberit.agilefant.util.IterationDataContainer;

public class IterationBusinessImpl implements IterationBusiness {

    private BacklogItemDAO backlogItemDAO;
    private BusinessThemeDAO businessThemeDAO;
    private IterationGoalDAO iterationGoalDAO;
    private IterationDAO iterationDAO;
    
    public IterationDataContainer getIterationContents(int iterationId) {
        Iteration iter = this.iterationDAO.get(iterationId);
        if(iter == null) {
            return null;
        }
        return this.getIterationContents(iter);
    }

    public IterationDataContainer getIterationContents(Iteration iter) {
        List<IterationGoal> goals = this.iterationGoalDAO.getGoalsByIteration(iter);
        
        IterationDataContainer iterData = new IterationDataContainer();
        iterData.setIterationGoals(goals);
        return iterData;
    }

    
    //AUTOGENERATED SETTERS
    
    public void setBacklogItemDAO(BacklogItemDAO backlogItemDAO) {
        this.backlogItemDAO = backlogItemDAO;
    }

    public void setBusinessThemeDAO(BusinessThemeDAO businessThemeDAO) {
        this.businessThemeDAO = businessThemeDAO;
    }

    public void setIterationGoalDAO(IterationGoalDAO iterationGoalDAO) {
        this.iterationGoalDAO = iterationGoalDAO;
    }
    
    public void setIterationDAO(IterationDAO iterationDAO) {
        this.iterationDAO = iterationDAO;
    }

}
