package fi.hut.soberit.agilefant.business.impl;

import java.util.ArrayList;
import java.util.List;

import fi.hut.soberit.agilefant.business.BacklogItemBusiness;
import fi.hut.soberit.agilefant.business.IterationBusiness;
import fi.hut.soberit.agilefant.db.IterationDAO;
import fi.hut.soberit.agilefant.db.IterationGoalDAO;
import fi.hut.soberit.agilefant.model.BacklogItem;
import fi.hut.soberit.agilefant.model.Iteration;
import fi.hut.soberit.agilefant.model.IterationGoal;
import fi.hut.soberit.agilefant.util.IterationDataContainer;

public class IterationBusinessImpl implements IterationBusiness {

    private BacklogItemBusiness backlogItemBusiness;
    private IterationGoalDAO iterationGoalDAO;
    private IterationDAO iterationDAO;
    
    public IterationDataContainer getIterationContents(int iterationId, boolean excludeBacklogItems) {
        Iteration iter = this.iterationDAO.get(iterationId);
        if(iter == null) {
            return null;
        }
        return this.getIterationContents(iter, excludeBacklogItems);
    }

    public IterationDataContainer getIterationContents(Iteration iter, boolean excludeBacklogItems) {
        List<IterationGoal> goals = this.iterationGoalDAO.getGoalsByIteration(iter);
        
        List<BacklogItem> blis = backlogItemBusiness.getBacklogItemsByBacklogWithCache(iter);
        
        IterationDataContainer iterData = new IterationDataContainer();
        iterData.setIterationGoals(goals);
        
        if(excludeBacklogItems) {
            return iterData;
        }
        //calculate efforts from pre-fetched backlog items
        for(IterationGoal goal : goals) {
            goal.setBacklogItems(new ArrayList<BacklogItem>());
            for(BacklogItem bli : blis) {
                if(bli.getIterationGoal() == goal) {
                    if(bli.getEffortLeft() != null) {
                        goal.getMetrics().getEffortLeft().add(bli.getEffortLeft());
                    }
                    if(bli.getEffortSpent() != null) {
                        goal.getMetrics().getEffortSpent().add(bli.getEffortSpent());
                    }
                    if(bli.getOriginalEstimate() != null) {
                        goal.getMetrics().getOriginalEstimate().add(bli.getOriginalEstimate());
                    }
                    goal.getMetrics().addTask(bli);
                    goal.getBacklogItems().add(bli);
                }
            }
        }
        List<BacklogItem> itemsWithoutGoal = new ArrayList<BacklogItem>();
        for(BacklogItem item : blis) {
            if(item.getIterationGoal() == null) {
                itemsWithoutGoal.add(item);
            }
        }
        iterData.setItemsWithoutGoal(itemsWithoutGoal);
        return iterData;
    }

    public int count() {
        return iterationDAO.count();
    }

    //AUTOGENERATED SETTERS

    public void setIterationGoalDAO(IterationGoalDAO iterationGoalDAO) {
        this.iterationGoalDAO = iterationGoalDAO;
    }
    
    public void setIterationDAO(IterationDAO iterationDAO) {
        this.iterationDAO = iterationDAO;
    }

    public void setBacklogItemBusiness(BacklogItemBusiness backlogItemBusiness) {
        this.backlogItemBusiness = backlogItemBusiness;
    }

}
