package fi.hut.soberit.agilefant.util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import fi.hut.soberit.agilefant.web.page.PageItem;

/**
 * Carrier class to bring lefthand menu data to action. 
 * @author rjokelai
 *
 */
public class MenuData {
    
    private List<PageItem> menuItems = new ArrayList<PageItem>();
    private Map<PageItem, Boolean> hasChildren = new HashMap<PageItem, Boolean>();
    private Map<PageItem, String> objectTypes = new HashMap<PageItem, String>();
    
    /*
     * Autogenerated list of setters and getters.
     */
    public List<PageItem> getMenuItems() {
        return menuItems;
    }

    public void setMenuItems(List<PageItem> menuItems) {
        this.menuItems = menuItems;
    }

    public Map<PageItem, Boolean> getHasChildren() {
        return hasChildren;
    }

    public void setHasChildren(Map<PageItem, Boolean> hasChildren) {
        this.hasChildren = hasChildren;
    }

    public Map<PageItem, String> getObjectTypes() {
        return objectTypes;
    }

    public void setObjectTypes(Map<PageItem, String> objectTypes) {
        this.objectTypes = objectTypes;
    }
}
