<script type="text/javascript" src="static/js/dynamics/Dynamics.events.js?<ww:text name="struts.agilefantReleaseId" />"></script>

<script type="text/javascript" src="static/js/utils/ArrayUtils.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/utils/ClassUtils.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/utils/Parsers.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/utils/XworkSerializer.js?<ww:text name="struts.agilefantReleaseId" />"></script>


<script type="text/javascript" src="static/js/dynamics/view/ViewPart.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/CommonSubView.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/CommonFragmentSubView.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/MessageDisplay.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/DynamicView.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/Table.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/Row.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/Cell.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/RowActions.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/TableConfiguration.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/Toggle.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/TableCaption.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/TableCellEditors.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/decorators.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/SplitPanel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/Tabs.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/Buttons.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/Button.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/ValidationManager.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/ConfirmationDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/ChangePasswordDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/LazyLoadedDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/UserSpentEffortWidget.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/LabelsView.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/LabelsIcon.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/AutoSuggest.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/SearchByTextWidget.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/StoryInfoWidget.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/StoryFiltersView.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/StateFilterWidget.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/SpentEffortWidget.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/Bubble.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/view/subviews/CellBubble.js?<ww:text name="struts.agilefantReleaseId" />"></script>

<script type="text/javascript" src="static/js/dynamics/model/CommonModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/BacklogModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/IterationModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/ProjectModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/ProductModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/StoryModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/TaskModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/UserModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/TeamModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/comparators.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/AssignmentModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/HourEntryModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/TaskSplitContainer.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/UserListContainer.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/TeamListContainer.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/HourEntryListContainer.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/PortfolioModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/LabelModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/DailyWorkModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/WorkQueueTaskModel.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/model/ModelFactory.js?<ww:text name="struts.agilefantReleaseId" />"></script>


<script type="text/javascript" src="static/js/dynamics/controller/CommonController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/BacklogController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TaskController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/AssignmentController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/StoryController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/IterationController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/StoryListController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/ProductController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/IterationRowController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/ProjectController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/ProjectRowController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/DailyWorkController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TasksWithoutStoryController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/DailyWorkStoryListController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/DailyWorkTasksWithoutStoryController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/WorkQueueController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TaskSplitDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/UserController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/StoryInfoBubble.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/UserListController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/UserRowController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TeamListController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TeamRowController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/CreateDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/TaskInfoDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/HourEntryController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/HourEntryListController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/StoryTreeController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/PortfolioController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/PortfolioRowController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/MyAssignmentsMenuController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/AdministrationMenuController.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/dynamics/controller/PersonalLoadController.js?<ww:text name="struts.agilefantReleaseId" />"></script>


<script type="text/javascript" src="static/js/autocomplete/autocompleteSearchBox.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteSelectedBox.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteRecent.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteBundle.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteDataProvider.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteSingleDialog.js?<ww:text name="struts.agilefantReleaseId" />"></script>
<script type="text/javascript" src="static/js/autocomplete/autocompleteInline.js?<ww:text name="struts.agilefantReleaseId" />"></script>
