package fi.hut.soberit.agilefant.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.opensymphony.xwork2.Action;
import com.opensymphony.xwork2.ActionSupport;

import fi.hut.soberit.agilefant.business.JSONBusiness;

@Component("jsonAction")
@Scope("prototype")
public class JSONAction extends ActionSupport {
    private static final long serialVersionUID = -6416506476416200967L;
    
    @Autowired
    private JSONBusiness jsonBusiness;
    
    private int backlogId;
//    private int backlogItemId;
    private String jsonData = "";

    @Override
    public String execute() throws Exception {
        return super.execute();
    }
    
    public String ajaxGetUserChooserJSON() {
        jsonData = jsonBusiness.getUserChooserJSON(backlogId);
        return Action.SUCCESS;
    }
    
    
    /* 
     * AUTOGENERATED LIST OF GETTERS AND SETTERS 
     */

    public int getBacklogId() {
        return backlogId;
    }

    public void setBacklogId(int backlogId) {
        this.backlogId = backlogId;
    }

//    public int getBacklogItemId() {
//        return backlogItemId;
//    }
//
//    public void setBacklogItemId(int backlogItemId) {
//        this.backlogItemId = backlogItemId;
//    }

    public void setJsonBusiness(JSONBusiness jsonBusiness) {
        this.jsonBusiness = jsonBusiness;
    }

    public String getJsonData() {
        return jsonData;
    }

    public void setJsonData(String jsonData) {
        this.jsonData = jsonData;
    }
}