package fi.hut.soberit.agilefant.web;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.opensymphony.xwork2.Action;
import com.opensymphony.xwork2.ActionSupport;


import fi.hut.soberit.agilefant.business.LabelBusiness;

@Component("labelAction")
@Scope("prototype")
public class LabelAction extends ActionSupport {
    
    private static final long serialVersionUID = 2732120227422713963L;

    private Integer labelId;
    
    @Autowired
    private LabelBusiness labelBusiness;
    
    public String delete(){
        System.out.println(getLabelId());
        labelBusiness.delete(getLabelId());
        return Action.SUCCESS;
    }
    
    // AUTOGENERATED

    public void setLabelBusiness(LabelBusiness labelBusiness) {
        this.labelBusiness = labelBusiness;
    }

    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    public Integer getLabelId() {
        return labelId;
    }


}
