package fi.hut.soberit.agilefant.web;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.opensymphony.xwork2.Action;
import com.opensymphony.xwork2.ActionSupport;

import fi.hut.soberit.agilefant.business.AgilefantWidgetBusiness;
import fi.hut.soberit.agilefant.business.WidgetCollectionBusiness;
import fi.hut.soberit.agilefant.model.AgilefantWidget;
import fi.hut.soberit.agilefant.model.WidgetCollection;

@Component("portletAction")
@Scope("prototype")
public class PortletAction extends ActionSupport implements ContextAware {

    private static final long serialVersionUID = -999270161618784027L;

    private int collectionId = 0;
    
    private WidgetCollection contents;
    private List<List<AgilefantWidget>> widgetGrid = new ArrayList<List<AgilefantWidget>>();

    private List<WidgetCollection> allCollections = new ArrayList<WidgetCollection>();
    
    @Autowired
    private AgilefantWidgetBusiness agilefantWidgetBusiness;
    
    @Autowired
    private WidgetCollectionBusiness widgetCollectionBusiness;
    
    public String retrieve() {
        if (collectionId == 0) {
            return Action.SUCCESS + "_projectPortfolio";
        }
        allCollections = widgetCollectionBusiness.getAllCollections();
        contents = widgetCollectionBusiness.retrieve(collectionId); 
        widgetGrid = agilefantWidgetBusiness.generateWidgetGrid(contents, 2);
        return Action.SUCCESS;
    }
    
    public String getPropertiesWidget() {
        contents = widgetCollectionBusiness.retrieve(collectionId);
        return Action.SUCCESS;
    }
    
    /*
     * AUTOGENERATED LIST OF SETTERS AND GETTERS
     */
    
    public String getContextName() {
        return "portfolio";
    }
    public int getContextObjectId() {
        return collectionId;
    }
    
    public WidgetCollection getContents() {
        return contents;
    }

    public void setContents(WidgetCollection contents) {
        this.contents = contents;
    }

    public List<List<AgilefantWidget>> getWidgetGrid() {
        return widgetGrid;
    }
    
    public int getViewId() {
        return collectionId;
    }
    
    public void setViewId(int viewId) {
        this.collectionId = viewId;
    }

    public int getCollectionId() {
        return collectionId;
    }

    public void setCollectionId(int collectionId) {
        this.collectionId = collectionId;
    }

    public List<WidgetCollection> getAllCollections() {
        return allCollections;
    }
}
